/*
PURPOSE: Fetch all the uploaded documents name 
*/

SELECT CPF.FILE_NAME FROM COM_REFFERAL_DATA CRD
INNER JOIN COM_COMMUNICATION CC
ON CC.ID = CRD.COMM_ID
INNER JOIN COM_PHYSICAL_FILE CPF
ON CPF.COMM_ID = CC.ID
WHERE CC.COMMUNICATION_NAME = 'MemberInvoiceQuote'
and CRD.ENTITY_ID = @claimNumber;

