/*
PURPOSE: Find Motor Policies have unpaid installments.
*/

SELECT TOP 50 PP.EXTERNAL_POLICY_NUMBER
FROM P_POLICY PP
JOIN P_POL_HEADER PPH       ON PP.ID = PPH.ACTIVE_POLICY_ID 
JOIN AC_INSTALLMENT AC      ON AC.POLICY_ID=PP.ID
JOIN  P_POLICY_CONTACT PPC  ON  PPC.POLICY_ID = PPH.ACTIVE_POLICY_ID
JOIN CN_PERSON CNP          ON CNP.CONTACT_ID = PPC.CONTACT_ID
JOIN CN_CONTACT_ADDRESS CNA ON CNA.CONTACT_ID = PPC.CONTACT_ID
JOIN CN_ADDRESS CNADD       ON CNADD.ID = CNA.ADRESS_ID
AND PPH.PRODUCT_ID = 1000000
AND PP.EXTERNAL_POLICY_NUMBER IS NOT NULL
and PP.STATUS_ID = 20
AND PP.RENEWAL_NUMBER=0
AND AC.INSTALLMENT_STATUS = 1
AND AC.DUE_DATE < GETDATE()
AND cnadd.STREET_NAME NOT LIKE '%[0-9]%' -- Filter out junk address 
AND  (select TOP 1 tvu.external_code from p_policy_lob ppl
	     JOIN P_POLICY_LOB_TO_LOB_ASSET PPLTLA ON PPL.ID = PPLTLA.POLICY_LOB_ID
         JOIN P_POLICY_LOB_ASSET PPLA          ON PPLTLA.LOB_ASSET_ID = PPLA.ID
         JOIN AS_Asset ass                     ON PPLA.LOB_ASSET_ID = ass.id
         JOIN AS_Vehicle asv                   ON ass.id = asv.Asset_id
         JOIN T_VEHICLE_USAGE tvu              ON tvu.id = asv.use_id
		WHERE PPH.ACTIVE_POLICY_ID = ppl.policy_id) = 'Private'
ORDER BY newid();
