/*
PURPOSE: Find a Home Building and Contents cover policy that is renewal and has at least one bank account
associated with the active policy holder.

This ensures that the member will have the bank account available for refund to source on a policy refund 
generated by an endorsement.
AUTHOR: Unknown
LAST UPDATED: Eric Li 2024-06-27 (AUNT-175)
*/
SELECT TOP 40 p.EXTERNAL_POLICY_NUMBER,
    ppc.contact_id as mainPH,
    p.id,
    FORMAT(PH.status_renewal_date,'dd/MM/yyyy HH:mm:ss') AS "Renewal Date",
    ca.house_nr,
    ca.street_name as street,
    ca.city_name as Suburb,
    (SELECT count(*) FROM p_policy_contact ppc2 WHERE ppc2.policy_id = PH.ACTIVE_POLICY_ID AND ppc2.policy_contact_role = 8) as coPHCount,
    ccba.CONTACT_ID as Payer,
    (SELECT top 1 cnt.telephone_number FROM cn_contact_telephone cnt 
     WHERE cnt.telephone_type = 4 AND cnt.discontinue_date is null  AND cnt.contact_id = ppc.contact_id) as MobilePhone,
    (SELECT top 1 CONCAT(cnt.TELEPHONE_PREFIX, cnt.telephone_number) FROM cn_contact_telephone cnt
     WHERE cnt.telephone_type = 3 AND cnt.discontinue_date is null AND cnt.contact_id = ppc.contact_id) as HomePhone
  FROM p_policy p
  JOIN p_pol_header ph                    ON p.id = ph.active_policy_id
  JOIN p_policy_contact ppc               ON ppc.policy_id = PH.ACTIVE_POLICY_ID
  JOIN cn_person cnp                      ON cnp.contact_id = ppc.contact_id
  JOIN t_collection_method tcm            ON tcm.id = p.COLLECTION_METHOD_ID
  JOIN t_payment_terms tpt                ON tpt.id = p.payment_term_id
  JOIN ac_installment ai                  ON ph.active_policy_id = ai.POLICY_ID
  JOIN p_policy_lob ppl                   ON PH.ACTIVE_POLICY_ID = ppl.policy_id
  JOIN P_POLICY_LOB_TO_LOB_ASSET PPLTLA   ON PPL.ID = PPLTLA.POLICY_LOB_ID
  JOIN P_POLICY_LOB_ASSET PPLA            ON PPLTLA.LOB_ASSET_ID = PPLA.ID
  JOIN AS_Asset ass                       ON PPLA.LOB_ASSET_ID = ass.id
  JOIN AS_Property asp                    ON ass.id = asp.ASSET_ID
  JOIN CN_ADDRESS ca                      ON asp.ADDRESS_ID = ca.ID
  JOIN cn_contact_bank_account ccba       ON p.POLICY_OWNER_BANK_ACCOUNT_ID = ccba.id
  JOIN p_cover pc_hcn                     ON p.id = pc_hcn.ENDORSMENT_ID
                                            AND pc_hcn.PARENT_COVER_ID is null
                                            AND pc_hcn.COVER_STATUS_ID = 20 -- Cover_status_id = 20  ensures that the cover is current
  JOIN t_product_line_option tplo_hcn     ON pc_hcn.product_option_id = tplo_hcn.id
  WHERE ph.product_id                     = 1000001 -- xx0 motor, xx1 home.
  AND (SELECT count(*)
    FROM ac_installment ai2
    WHERE ai2.POLICY_ID = ph.active_policy_id
   AND   ai2.installment_status IN (3,5)  -- 3=Paid, 5=Rejected
  ) = 0
  AND (SELECT count(contact_ID) as "Bank Account Count"
     FROM CN_CONTACT_BANK_ACCOUNT ccba
     WHERE ccba.CONTACT_ID = ppc.contact_id
     AND ccba.BANK_NAME not in ('AMEX', 'MASTERCARD', 'VISA')
     AND ccba.discontinue_date is null
     GROUP BY ccba.contact_ID) >= 1
  AND ppc.policy_contact_role in (6, 8) -- 6=Policyholder 8=co-Policyholder
  AND ccba.CONTACT_ID = ppc.CONTACT_ID

  AND ph.status_renewal_date  between DATEADD(day, 14, convert(date, GETDATE())) and DATEADD(day, 28, convert(date, GETDATE())) 
  AND PH.MAIN_RENEWAL_DATE    > ph.status_renewal_date
  AND ai.INSTALLMENT_STATUS   = 1      -- 1=Pending
  AND asp.building_year       > 1900 -- Avoid bug B2C-1270 (Marked "Done" as no interest in fix from PO short term)
  AND p.status_ID             = 20   -- 20=Policy (indicates active, not "Cancelled Policy", "Proposal" etc)
  AND ph.status_ID            = 20   -- 20=Policy (indicates active, not "Cancelled Policy", "Proposal" etc)
  AND p.ENDORSMENT_TYPE_ID    = 10   -- 10 Policy Renewal
  AND p.payment_term_id       = 1    -- 1 is Yearly Direct Debit | 4 is Monthly Direct Debit | 6 = Yearly Cash | 1000002 = Monthly Credit Card
  AND p.collection_method_ID  = 2    -- 2 is Direct Debit by Bank Account | 1 Annual Cash | 4 is Direct Debit by Credit Card
  AND ph.STATUS_RENEWAL_DATE  IS NOT NULL
  AND cnp.date_of_birth       IS NOT NULL -- helps screen out company policies.
  -- Must have home and contents
  AND tplo_hcn.EXTERNAL_CODE = 'HCN'
  AND (SELECT count(*) 
        FROM p_cover pc2 
        JOIN t_product_line_option tplo2 ON pc2.product_option_id = tplo2.id 
        JOIN T_PRODUCT_LINE_OPTION_TYPE tplot2 ON tplot2.id = tplo2.option_type_id
       WHERE pc2.PARENT_COVER_ID is null AND p.id=pc2.ENDORSMENT_ID AND tplot2.external_code = 'HB' AND pc2.COVER_STATUS_ID = 20) = 1
ORDER BY newid()
;