/*
PURPOSE: Get latest description of home and motor endorsement type and reason for a given policy number

AUTHOR: Eric Li
LAST UPDATED: 2023-10-11
*/
SELECT
    P.EXTERNAL_POLICY_NUMBER
    ,PER.ENDORSMENT_REASON_ID
    ,ER.[DESCRIPTION] AS 'ENDORSMENT_REASON'
    ,PER.REMARKS
    ,TET.DESCRIPTION AS 'ENDORSMENT_TYPE'
FROM
    P_POL_HEADER AS PH
JOIN
    P_POLICY AS P ON P.ID = PH.ACTIVE_POLICY_ID
LEFT JOIN
    P_POLICY_ENDORSMENT_REASON AS PER ON PER.POLICY_ID = P.ID
LEFT JOIN
    T_ENDORSMENT_REASON AS ER ON ER.ID = PER.ENDORSMENT_REASON_ID
LEFT JOIN
    T_ENDORSMENT_TYPE AS TET ON TET.ID = P.ENDORSMENT_TYPE_ID
WHERE
    P.EXTERNAL_POLICY_NUMBER = @policyNumber
    AND P.POLICY_VERSION_NR IS NOT NULL
ORDER BY
    P.POLICY_VERSION_NR DESC;