using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rac.TestAutomation.Common
{
    public class AddressBuilder : EntityBuilder<Address, AddressBuilder>
    {
        public AddressBuilder() { }

        public AddressBuilder(Address address)
        {
            WithStreetNumber(address.StreetNumber);
            WithStreetOrPOBox(address.StreetOrPOBox);
            WithSuburb(address.Suburb);
            WithPostCode(address.PostCode);
            WithPDM(address.IsPreferredDeliveryMethod);
        }

        public AddressBuilder WithStreetOrPOBox(string streetName)
        {
            Set(x => x.StreetOrPOBox, streetName);
            return this;
        }

        public AddressBuilder WithoutStreetName()
        {
            return WithStreetOrPOBox(null);
        }

        public AddressBuilder WithStreetNumber(string streetNumber)
        {
            Set(x => x.StreetNumber, streetNumber);
            return this;
        }

        public AddressBuilder WithoutStreetNumber()
        {
            return WithStreetNumber(null);
        }

        public AddressBuilder WithSuburb(string suburb)
        {
            Set(x => x.Suburb, suburb);
            return this;
        }

        public AddressBuilder WithoutSuburb()
        {
            return WithSuburb(null);
        }

        public AddressBuilder WithPostCode(string postCode)
        {
            Set(x => x.PostCode, postCode);
            return this;
        }

        public AddressBuilder WithoutPostCode()
        {
            return WithPostCode(null);
        }

        public AddressBuilder WithPDM(bool isPreferredDeliveryMethod)
        {
            Set(x => x.IsPreferredDeliveryMethod, isPreferredDeliveryMethod);
            return this;
        }

        public AddressBuilder InitialiseRandomMailingAddress()
        {
            var address = GetRandomAddress();
            return WithStreetNumber(address.StreetNumber)
                .WithStreetOrPOBox(address.StreetOrPOBox)
                .WithSuburb(address.Suburb)
                .WithPostCode(address.PostCode)
                .WithPDM(false);
        }

        protected override Address BuildEntity()
        {
            return new Address
            {
                StreetNumber = GetOrDefault(x => x.StreetNumber),
                StreetOrPOBox = GetOrDefault(x => x.StreetOrPOBox),
                Suburb = GetOrDefault(x => x.Suburb),
                PostCode = GetOrDefault(x => x.PostCode),
                IsPreferredDeliveryMethod = GetOrDefault(x => x.IsPreferredDeliveryMethod)
            };
        }

        /// <summary>
        /// The list in this method was generated by querying the Shield database
        /// for current policies with QAS verified addresses. This list will have
        /// little risk of being outdated as addresses do not often change. If an
        /// address is found to be problematic though, then please feel free to
        /// replace it.
        /// 
        /// The addresses chosen below were selected randomly, so there is no pattern
        /// or distribution to be maintained.
        /// </summary>
        /// <returns></returns>
        private static Address GetRandomAddress()
        {
            var addressList = new[]
            {
                new Address(){StreetNumber="109",StreetOrPOBox="Lorimer Rd",Suburb="MUNSTER",PostCode="6166"},
                new Address(){StreetNumber="100A",StreetOrPOBox="Nollamara Ave",Suburb="NOLLAMARA",PostCode="6061"},
                new Address(){StreetNumber="111",StreetOrPOBox="Chamberlain St",Suburb="GOSNELLS",PostCode="6110"},
                new Address(){StreetNumber="9",StreetOrPOBox="Penguin Cl",Suburb="HEATHRIDGE",PostCode="6027"},
                new Address(){StreetNumber="23",StreetOrPOBox="Loggerhead Rd",Suburb="ALKIMOS",PostCode="6038"},
                new Address(){StreetNumber="71",StreetOrPOBox="Hopkinson Way",Suburb="WILSON",PostCode="6107"},
                new Address(){StreetNumber="130",StreetOrPOBox="Badgerup Ave",Suburb="LAKELANDS",PostCode="6180"},
                new Address(){StreetNumber="89a",StreetOrPOBox="Lockhart St",Suburb="COMO",PostCode="6152"},
                new Address(){StreetNumber="15",StreetOrPOBox="Berrington Pass",Suburb="QUINNS ROCKS",PostCode="6030"},
                new Address(){StreetNumber="6",StreetOrPOBox="Qualen Mews",Suburb="DIANELLA",PostCode="6059"},
                new Address(){StreetNumber="60",StreetOrPOBox="Evandale St",Suburb="FLOREAT",PostCode="6014"},
                new Address(){StreetNumber="20",StreetOrPOBox="Lexington Prom",Suburb="CAVERSHAM",PostCode="6055"},
                new Address(){StreetNumber="98",StreetOrPOBox="Pectoral Prom",Suburb="ALKIMOS",PostCode="6038"},
                new Address(){StreetNumber="1",StreetOrPOBox="Shin Way",Suburb="KINROSS",PostCode="6028"},
                new Address(){StreetNumber="2",StreetOrPOBox="Welford Way",Suburb="SUCCESS",PostCode="6164"},
                new Address(){StreetNumber="38",StreetOrPOBox="Brightlands Cct",Suburb="CARRAMAR",PostCode="6031"},
                new Address(){StreetNumber="19",StreetOrPOBox="Bronze St",Suburb="EGLINTON",PostCode="6034"},
                new Address(){StreetNumber="81",StreetOrPOBox="Powell Cres",Suburb="BROOKDALE",PostCode="6112"},
                new Address(){StreetNumber="155",StreetOrPOBox="Acton Ave",Suburb="RIVERVALE",PostCode="6103"},
                new Address(){StreetNumber="290",StreetOrPOBox="Hart Dr",Suburb="CHITTERING",PostCode="6084"},
                new Address(){StreetNumber="24",StreetOrPOBox="Beresford Gdns",Suburb="SWAN VIEW",PostCode="6056"},
                new Address(){StreetNumber="49a",StreetOrPOBox="Hastings St",Suburb="SCARBOROUGH",PostCode="6019"},
                new Address(){StreetNumber="49",StreetOrPOBox="Bloodwood Cir",Suburb="SOUTH LAKE",PostCode="6164"},
                new Address(){StreetNumber="22",StreetOrPOBox="Crouchley Ct",Suburb="BROADWATER",PostCode="6280"},
                new Address(){StreetNumber="378",StreetOrPOBox="Walcott St",Suburb="COOLBINIA",PostCode="6050"},
                new Address(){StreetNumber="43",StreetOrPOBox="Vermont St",Suburb="NOLLAMARA",PostCode="6061"},
                new Address(){StreetNumber="37",StreetOrPOBox="Belvedere Rd",Suburb="HAMERSLEY",PostCode="6022"},
                new Address(){StreetNumber="8",StreetOrPOBox="Erickson Pass",Suburb="ELLENBROOK",PostCode="6069"},
                new Address(){StreetNumber="5",StreetOrPOBox="Prince Ct",Suburb="QUINNS ROCKS",PostCode="6030"},
                new Address(){StreetNumber="21",StreetOrPOBox="Thomas Way",Suburb="KARRINYUP",PostCode="6018"},
                new Address(){StreetNumber="3",StreetOrPOBox="Wentworth St",Suburb="YANCHEP",PostCode="6035"},
                new Address(){StreetNumber="6",StreetOrPOBox="Reilly St",Suburb="ORELIA",PostCode="6167"},
                new Address(){StreetNumber="58",StreetOrPOBox="Ipsen St",Suburb="MANJIMUP",PostCode="6258"},
                new Address(){StreetNumber="41",StreetOrPOBox="Clydesdale St",Suburb="COMO",PostCode="6152"},
                new Address(){StreetNumber="200",StreetOrPOBox="Brentwood Rd",Suburb="KENWICK",PostCode="6107"},
                new Address(){StreetNumber="5",StreetOrPOBox="Cribb Ct",Suburb="REDCLIFFE",PostCode="6104"},
                new Address(){StreetNumber="56C",StreetOrPOBox="Leonard St",Suburb="VICTORIA PARK",PostCode="6100"},
                new Address(){StreetNumber="39",StreetOrPOBox="Crossman Rd",Suburb="RANFORD",PostCode="6390"},
                new Address(){StreetNumber="6",StreetOrPOBox="John St",Suburb="COTTESLOE",PostCode="6011"},
                new Address(){StreetNumber="12",StreetOrPOBox="Jubaea Ct",Suburb="CANNING VALE",PostCode="6155"},
                new Address(){StreetNumber="10",StreetOrPOBox="Pepin Ct",Suburb="JOONDALUP",PostCode="6027"},
                new Address(){StreetNumber="1",StreetOrPOBox="Greenfields Rd",Suburb="HARVEY",PostCode="6220"},
                new Address(){StreetNumber="4",StreetOrPOBox="Ratcliff View",Suburb="OCEAN BEACH",PostCode="6333"},
                new Address(){StreetNumber="8",StreetOrPOBox="Veresdale Rtt",Suburb="COODANUP",PostCode="6210"},
                new Address(){StreetNumber="35",StreetOrPOBox="Amazon Dr",Suburb="BALDIVIS",PostCode="6171"},
                new Address(){StreetNumber="667",StreetOrPOBox="Hay St",Suburb="JOLIMONT",PostCode="6014"},
                new Address(){StreetNumber="2a",StreetOrPOBox="Tyson Pl",Suburb="QUINNS ROCKS",PostCode="6030"},
                new Address(){StreetNumber="11",StreetOrPOBox="Kimber Pl",Suburb="MOUNT HELENA",PostCode="6082"},
                new Address(){StreetNumber="11",StreetOrPOBox="Protea Ct",Suburb="STONEVILLE",PostCode="6081"},
                new Address(){StreetNumber="220",StreetOrPOBox="Loftus St",Suburb="North Perth",PostCode="6006"},
                new Address(){StreetNumber="9",StreetOrPOBox="Winnipeg Ct",Suburb="GREENFIELDS",PostCode="6210"},
                new Address(){StreetNumber="28a",StreetOrPOBox="Badrick St",Suburb="WARWICK",PostCode="6024"},
                new Address(){StreetNumber="17",StreetOrPOBox="Otway St",Suburb="SWANBOURNE",PostCode="6010"},
                new Address(){StreetNumber="53",StreetOrPOBox="Capel St",Suburb="KIRUP",PostCode="6251"},
                new Address(){StreetNumber="105A",StreetOrPOBox="Welwyn Ave",Suburb="SALTER POINT",PostCode="6152"},
                new Address(){StreetNumber="115",StreetOrPOBox="Guildford Rd",Suburb="MAYLANDS",PostCode="6051"},
                new Address(){StreetNumber="23",StreetOrPOBox="Molonglo Cres",Suburb="BALDIVIS",PostCode="6171"},
                new Address(){StreetNumber="96",StreetOrPOBox="Third Ave",Suburb="MOUNT LAWLEY",PostCode="6050"},
                new Address(){StreetNumber="10",StreetOrPOBox="Laura Gra",Suburb="BRABHAM",PostCode="6055"},
                new Address(){StreetNumber="25",StreetOrPOBox="Flinders Cres",Suburb="ABBEY",PostCode="6280"},
                new Address(){StreetNumber="22",StreetOrPOBox="Rummer Way",Suburb="BATEMAN",PostCode="6150"},
                new Address(){StreetNumber="11",StreetOrPOBox="Harlequin Mews",Suburb="GREENFIELDS",PostCode="6210"},
                new Address(){StreetNumber="8",StreetOrPOBox="Arrowsmith Ave",Suburb="ELLENBROOK",PostCode="6069"},
                new Address(){StreetNumber="229",StreetOrPOBox="Hector St",Suburb="TUART HILL",PostCode="6060"},
                new Address(){StreetNumber="10",StreetOrPOBox="Gantheaume Pde",Suburb="SECRET HARBOUR",PostCode="6173"},
                new Address(){StreetNumber="65",StreetOrPOBox="Caridean St",Suburb="HEATHRIDGE",PostCode="6027"},
                new Address(){StreetNumber="4",StreetOrPOBox="Marquis Ct",Suburb="GOSNELLS",PostCode="6110"},
                new Address(){StreetNumber="25",StreetOrPOBox="Swan Rd",Suburb="MAHOGANY CREEK",PostCode="6072"},
                new Address(){StreetNumber="7c",StreetOrPOBox="Welburn St",Suburb="NOLLAMARA",PostCode="6061"},
                new Address(){StreetNumber="22",StreetOrPOBox="Glenmaggie Cct",Suburb="Success",PostCode="6164"},
                new Address(){StreetNumber="4",StreetOrPOBox="Silver Princess Way",Suburb="JANE BROOK",PostCode="6056"},
                new Address(){StreetNumber="4",StreetOrPOBox="Montrose Way",Suburb="NOLLAMARA",PostCode="6061"},
                new Address(){StreetNumber="3",StreetOrPOBox="Correa Pass",Suburb="SUCCESS",PostCode="6164"},
                new Address(){StreetNumber="10",StreetOrPOBox="Penryn Ave",Suburb="CITY BEACH",PostCode="6015"},
                new Address(){StreetNumber="34",StreetOrPOBox="Glenmere Rd",Suburb="WARWICK",PostCode="6024"},
                new Address(){StreetNumber="25",StreetOrPOBox="Pomodora Ave",Suburb="LANDSDALE",PostCode="6065"},
                new Address(){StreetNumber="18B",StreetOrPOBox="Claygate Rd",Suburb="HAMILTON HILL",PostCode="6163"},
                new Address(){StreetNumber="92a",StreetOrPOBox="Edney Rd",Suburb="HIGH WYCOMBE",PostCode="6057"},
                new Address(){StreetNumber="28a",StreetOrPOBox="Koolyanga Rd",Suburb="MULLALOO",PostCode="6027"},
                new Address(){StreetNumber="111",StreetOrPOBox="Anaconda Dr",Suburb="GOSNELLS",PostCode="6110"}
            };

            return addressList.OrderBy(t => Guid.NewGuid()).First();
        }
    }
}
